name: Optimize
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  svgs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Optimize
        uses: ericcornelissen/svgo-action@v3
        id: svgo
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          svgo-version: 3
          svgo-config: svgo.config.js
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{steps.svgo.outputs.DID_OPTIMIZE}}
        with:
          commit_message: "fix: optimize ${{steps.svgo.outputs.OPTIMIZED_COUNT}} svg(s)"
