name: Optimize
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  svgs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install
        run: npm ci
      - name: Optimize
        run: npm run svgo
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: optimize svgs"
