name: 'Deploy'
on:
  push:
    branches:
      - main
jobs:
  gh-pages:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install and Build
        run: |
          npm ci
          npm run build
      - name: Create index file
        run: mv dist/sprite.css.html dist/index.html
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: dist
