name: 'Publish release'
on:
  create:
    tags:
      - '@haiilo/catalyst-icons@*'
  workflow_run:
    workflows:
      - 'Create release'
    types:
      - completed
jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: '17'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install and Build
        run: |
          npm ci
          npm run build
      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: package.json
