name: 'Tag'
on:
  push:
    tags:
      - "@haiilo/catalyst-icons@*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish to GitHub
        uses: softprops/action-gh-release@v1
